In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt 

from sklearn.preprocessing import LabelEncoder, StandardScaler
from sklearn.metrics import accuracy_score as ACC

from keras import layers
from keras.layers import RNN, Dense, Dropout, BatchNormalization
from keras import Sequential, layers, Input, callbacks

import warnings
warnings.filterwarnings('ignore')

In [3]:
train_df = pd.read_csv('data/train_df')

FileNotFoundError: [Errno 2] No such file or directory: 'data/train_df'

In [ ]:
train_df

In [110]:
# Importing all the datasets
train_A = pd.read_csv('data/train_A.csv')
train_B = pd.read_csv('data/train_B.csv')
train_C = pd.read_csv('data/train_C.csv')

val_A = pd.read_csv('data/val_A.csv')
val_B = pd.read_csv('data/val_B.csv')
val_C = pd.read_csv('data/val_C.csv')

test_A = pd.read_csv('data/test_A.csv')
test_B = pd.read_csv('data/test_B.csv')
test_C = pd.read_csv('data/test_C.csv')

In [111]:

datasets = [train_A, val_A, test_A, 
            train_B, val_B, test_B, 
            train_C, val_C, test_C]


In [113]:
val_C

char                                             dialog    i  \
0            DENETHOR                    ['son', 'spent', 'line', 'end']  0.0   
1          WITCH KING                                          ['break']  1.0   
2    MERRY and PIPPIN                        ['come', 'green', 'dragon']  NaN   
3                 SAM               ['special', 'best', 'salt', 'shire']  NaN   
4              ELROND  ['stranger', 'distant', 'land', 'friend', 'old...  NaN   
..                ...                                                ...  ...   
353           GANDALF                    ['inde', 'good', 'yes', 'good']  NaN   
354               SAM                                 ['strider', 'get']  NaN   
355           GANDALF                                           ['know']  NaN   
356            GOLLUM  ['dead', 'rotten', 'elv', 'men', 'orcs', 'grea...  NaN   
357            GOLLUM                                        ['aaaaahh']  NaN   

       a    g    r    d    o    l    h    c  
0    1.0  0.0  1.0  0.0  0.0  0.0  1.0  1.0  
1    1.0  1.0  0.0  1.0  1.0  1.0  0.0  0.0  
2    NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  
3    NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  
4    NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  
..   ...  ...  ...  ...  ...  ...  ...  ...  
353  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  
354  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  
355  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  
356  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  
357  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  

[358 rows x 11 columns]

In [96]:
imp_char = ["FRODO", "SAM", "GANDALF", "PIPPIN", "MERRY", "GOLLUM", "GIMLI", "THEODEN", "FARAMIR", "ARAGORN"]

# Creating a common label for the characters not of interest
def common_label_removal(data):
    mask = data["char"].isin(imp_char)
    data.loc[~ mask, "char"] = "Rest"
    mask2 = data['char'] == 'Rest'
    data = data[~mask2]
    return data

def x_y_split(data):
    y_data = data['char']
    x_data = data.drop(columns=['char', 'dialog'])
    return x_data, y_data

def char_2_num(y_data):
    encoder = LabelEncoder()
    y_data = y_data.values.reshape(-1, 1)
    encoded_data = encoder.fit_transform(y_data)
    names = list(encoder.inverse_transform(np.unique(encoded_data)))
    print(names)
    print(np.unique(encoded_data))
    return encoded_data, names

def preprocessing(data):
    data = common_label_removal(data)
    x_data, y_data = x_y_split(data)
    y_data = char_2_num(y_data)
    return x_data, y_data

for i in range(len(datasets)):
    datasets[i] = preprocessing(datasets[i])

['ARAGORN', 'FARAMIR', 'FRODO', 'GANDALF', 'GIMLI', 'GOLLUM', 'MERRY', 'PIPPIN', 'SAM', 'THEODEN']
[0 1 2 3 4 5 6 7 8 9]
['ARAGORN', 'FARAMIR', 'FRODO', 'GANDALF', 'GIMLI', 'GOLLUM', 'MERRY', 'PIPPIN', 'SAM', 'THEODEN']
[0 1 2 3 4 5 6 7 8 9]
['ARAGORN', 'FARAMIR', 'FRODO', 'GANDALF', 'GIMLI', 'GOLLUM', 'MERRY', 'PIPPIN', 'SAM', 'THEODEN']
[0 1 2 3 4 5 6 7 8 9]
['ARAGORN', 'FARAMIR', 'FRODO', 'GANDALF', 'GIMLI', 'GOLLUM', 'MERRY', 'PIPPIN', 'SAM', 'THEODEN']
[0 1 2 3 4 5 6 7 8 9]
['ARAGORN', 'FARAMIR', 'FRODO', 'GANDALF', 'GIMLI', 'GOLLUM', 'MERRY', 'PIPPIN', 'SAM', 'THEODEN']
[0 1 2 3 4 5 6 7 8 9]
['ARAGORN', 'FARAMIR', 'FRODO', 'GANDALF', 'GIMLI', 'GOLLUM', 'MERRY', 'PIPPIN', 'SAM', 'THEODEN']
[0 1 2 3 4 5 6 7 8 9]
['ARAGORN', 'FARAMIR', 'FRODO', 'GANDALF', 'GIMLI', 'GOLLUM', 'MERRY', 'PIPPIN', 'SAM', 'THEODEN']
[0 1 2 3 4 5 6 7 8 9]
['ARAGORN', 'FARAMIR', 'FRODO', 'GANDALF', 'GIMLI', 'GOLLUM', 'MERRY', 'PIPPIN', 'SAM', 'THEODEN']
[0 1 2 3 4 5 6 7 8 9]
['ARAGORN', 'FARAMIR', 'FRODO', 

In [98]:
datasets[4][0]

word_1     word_2     word_3      word_4      word_5      word_6  \
3     9.115310   7.688281   9.286860    7.688242    7.771596    8.520296   
5    10.334905   9.189292   9.307186   10.164455   10.622702    9.824760   
7    10.472886   7.548090  10.214078   13.348991  100.000000  100.000000   
8     9.116848   8.790980   8.506043    9.787569    7.771913    9.307035   
9     7.316826  10.031580   9.539154    9.536426    9.331389    9.984630   
..         ...        ...        ...         ...         ...         ...   
353   8.749244   6.519113   7.443720    7.932528    9.826411   10.804083   
354   7.784269   8.413539   7.753873    8.329385    9.464520    9.546089   
355  11.961802   8.855804   9.939498    8.334146    9.954555    9.503821   
356   9.044804   7.706784  10.586007    9.485938    8.543586   10.895023   
357  11.732788   7.056313  13.205585  100.000000  100.000000  100.000000   

         word_7      word_8      word_9     word_10  ...  word_161  word_162  \
3      9.904340    9.202535    8.142834    8.952360  ...       100       100   
5     11.237732    8.705162    9.194898   12.743243  ...       100       100   
7    100.000000  100.000000  100.000000  100.000000  ...       100       100   
8      7.550519    9.115552    7.722796    6.736122  ...       100       100   
9     12.776522  100.000000  100.000000  100.000000  ...       100       100   
..          ...         ...         ...         ...  ...       ...       ...   
353    8.896856   10.560899    9.064045    8.195283  ...       100       100   
354   10.911575   13.359749  100.000000  100.000000  ...       100       100   
355   12.866217  100.000000  100.000000  100.000000  ...       100       100   
356    9.503613   11.318297    7.783121   11.634004  ...       100       100   
357  100.000000  100.000000  100.000000  100.000000  ...       100       100   

     word_163  word_164  word_165  word_166  word_167  word_168  word_169  \
3         100       100       100       100       100       100       100   
5         100       100       100       100       100       100       100   
7         100       100       100       100       100       100       100   
8         100       100       100       100       100       100       100   
9         100       100       100       100       100       100       100   
..        ...       ...       ...       ...       ...       ...       ...   
353       100       100       100       100       100       100       100   
354       100       100       100       100       100       100       100   
355       100       100       100       100       100       100       100   
356       100       100       100       100       100       100       100   
357       100       100       100       100       100       100       100   

     word_170  
3         100  
5         100  
7         100  
8         100  
9         100  
..        ...  
353       100  
354       100  
355       100  
356       100  
357       100  

[254 rows x 170 columns]

In [103]:
A_tra_X =datasets[0][0]
A_tra_y =datasets[0][1][0]
A_val_X =datasets[1][0]
A_tra_y=datasets[1][1][0]
A_tar_X=datasets[2][0]
A_tar_y=datasets[2][1][0]

B_tra_X =datasets[3][0]
B_tra_y =datasets[3][1][0]
B_val_X =datasets[4][0]
B_val_y=datasets[4][1][0]
B_tar_X=datasets[5][0]
B_tar_y=datasets[5][1][0]

C_tra_X =datasets[6][0]
C_tra_y =datasets[6][1][0]
C_val_X =datasets[7][0]
C_tra_y=datasets[7][1][0]
C_tar_X=datasets[8][0]
C_tar_y=datasets[8][1][0]

In [105]:
C_val_X

i   a   g   r   d   o   l   h   c
3   NaN NaN NaN NaN NaN NaN NaN NaN NaN
5   NaN NaN NaN NaN NaN NaN NaN NaN NaN
7   NaN NaN NaN NaN NaN NaN NaN NaN NaN
8   NaN NaN NaN NaN NaN NaN NaN NaN NaN
9   NaN NaN NaN NaN NaN NaN NaN NaN NaN
..   ..  ..  ..  ..  ..  ..  ..  ..  ..
353 NaN NaN NaN NaN NaN NaN NaN NaN NaN
354 NaN NaN NaN NaN NaN NaN NaN NaN NaN
355 NaN NaN NaN NaN NaN NaN NaN NaN NaN
356 NaN NaN NaN NaN NaN NaN NaN NaN NaN
357 NaN NaN NaN NaN NaN NaN NaN NaN NaN

[254 rows x 9 columns]

In [71]:
def naive_benchmark_MonC(y):
    accuracy_list = []
    for i in range(0,1000,1):
        naive_rand_pred = np.random.randint(0,12,size=(len(y)))
        accuracy_sel = ACC(naive_rand_pred, y)
        accuracy_list.append(accuracy_sel)
    return np.mean(accuracy_list)

In [74]:
naive_benchmark_MonC(A_tar_y)

0.08305128205128205

In [59]:
def naive_benchmark_MajC(y):
    pred_MCNB =np.repeat(2,len(y))
    return ACC(pred_MCNB, y)

In [75]:
naive_benchmark_MajC(A_tar_y)

0.1752136752136752

<h2> 4. Modelling  </h2>
<h3> ANN on dataset A</h3>

In [80]:
scaler = StandardScaler()
A1 = scaler.fit_transform(A_tra_X)
A2 = scaler.transform(A_val_X)
A3 = scaler.transform(A_tar_X)

Y1 = np.eye(11)[A_tra_y]
Y2 = np.eye(11)[A_tra_y]
Y3 = np.eye(11)[A_tra_y]

In [82]:
A1.shape

(1147, 20)

In [83]:
model = keras.Sequential([
    layers.Dense(8, activation='relu',input_dim=20),
    layers.BatchNormalization(),
    layers.Dropout(rate=0.3),
    layers.Dense(8, activation='selu'),
    # layers.BatchNormalization(),
    # layers.Dropout(0.3),
    # layers.Dense(254, activation='softmax'),
    layers.Dense(11)
])
model.compile(optimizer='adam',
              loss = 'categorical_crossentropy',
              metrics=['accuracy']
              )

early_stopping = callbacks.EarlyStopping(
    min_delta=0.001, # minimium amount of change to count as an improvement
    patience=35, # how many epochs to wait before stopping
    restore_best_weights=True,
)
model.fit(A1, Y1, 
          validation_data= (A2, Y2),
          epochs=200, batch_size=5, 
          callbacks=early_stopping
          )

Epoch 1/200
230/230 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.0814 - loss: 6.8511 - val_accuracy: 0.0968 - val_loss: 6.5929
Epoch 2/200
230/230 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.0904 - loss: 6.9825 - val_accuracy: 0.0942 - val_loss: 6.3822
Epoch 3/200
230/230 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.0871 - loss: 6.7383 - val_accuracy: 0.0959 - val_loss: 6.4289
Epoch 4/200
230/230 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.0815 - loss: 6.1875 - val_accuracy: 0.0924 - val_loss: 6.2460
Epoch 5/200
230/230 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.0878 - loss: 6.6945 - val_accuracy: 0.0959 - val_loss: 6.3010
Epoch 6/200
230/230 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.0693 - loss: 6.4726 - val_accuracy: 0.0837 - val_loss: 6.2078
Epoch 7/200
230/230 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.0677 - loss: 5.7929 - val_accuracy: 0.0689 - val_loss: 6.0944
Epoch 8/200
230/230 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.0727 - loss: 5.2013 - val_accu

<h3> RNN on dataset B

In [85]:
def reshaper(X, timeSteps=None):
    X = pd.DataFrame(X)
    new_Xs = [np.array(X[timeSteps:])]
    print(X.shape)

    for i in range(1, timeSteps+1,1):
        shift_X  = np.array(X.shift(i))
        new_Xs.append(shift_X[timeSteps:])

    X_reshaped = np.stack(new_Xs, axis=1)
    return X_reshaped

In [86]:
# B1 = reshaper()
# B2
# B3

In [87]:
# model = keras.Sequential([
#     layers.Dense(8, activation='relu',input_dim=20),
#     layers.BatchNormalization(),
#     layers.Dropout(rate=0.3),
#     layers.Dense(8, activation='selu'),
#     # layers.BatchNormalization(),
#     # layers.Dropout(0.3),
#     # layers.Dense(254, activation='softmax'),
#     layers.Dense(11)
# ])
# model.compile(optimizer='adam',
#               loss = 'categorical_crossentropy',
#               metrics=['accuracy']
#               )

# early_stopping = callbacks.EarlyStopping(
#     min_delta=0.001, # minimium amount of change to count as an improvement
#     patience=35, # how many epochs to wait before stopping
#     restore_best_weights=True,
# )
# model.fit(A1, Y1, 
#           validation_data= (A2, Y2),
#           epochs=200, batch_size=5, 
#           callbacks=early_stopping
#           )

In [114]:
B_tra_X

word_1     word_2     word_3      word_4      word_5      word_6  \
1      7.936516  11.274338  12.535010  100.000000  100.000000  100.000000   
2      7.807208   7.082729  10.126812    9.273765    7.891686    8.183380   
3      8.937764   7.750165   8.915595    8.662035    6.803154    6.460621   
4     10.943976   7.265589  10.792604   13.414934  100.000000  100.000000   
5     11.383319   8.229084  10.143223    7.550912    9.198028    7.539784   
...         ...        ...        ...         ...         ...         ...   
1663   8.870296   9.705757   7.965269    6.652018    8.039692    8.533687   
1664   8.342788   7.922681   8.421476    8.497047    9.581614   10.287869   
1665   9.338175  12.174479   7.489946   10.374016    8.709492    8.717413   
1670   9.798004   8.581070   9.354257   13.826755  100.000000  100.000000   
1671   8.133518  10.620996   7.529290    7.960512    9.321564    8.349144   

          word_7      word_8      word_9     word_10  ...  word_161  word_162  \
1     100.000000  100.000000  100.000000  100.000000  ...       100       100   
2      10.324145    7.371899    9.027041    7.104752  ...       100       100   
3      11.343762  100.000000  100.000000  100.000000  ...       100       100   
4     100.000000  100.000000  100.000000  100.000000  ...       100       100   
5       7.757065    8.074544    7.358045    7.983031  ...       100       100   
...          ...         ...         ...         ...  ...       ...       ...   
1663    8.299333   11.232112   12.855322  100.000000  ...       100       100   
1664    9.037190    7.900794   11.145840    7.884370  ...       100       100   
1665    8.328237    9.383992    6.920962    7.234212  ...       100       100   
1670  100.000000  100.000000  100.000000  100.000000  ...       100       100   
1671   10.677260    9.012439    9.785184    7.911406  ...       100       100   

      word_163  word_164  word_165  word_166  word_167  word_168  word_169  \
1          100       100       100       100       100       100       100   
2          100       100       100       100       100       100       100   
3          100       100       100       100       100       100       100   
4          100       100       100       100       100       100       100   
5          100       100       100       100       100       100       100   
...        ...       ...       ...       ...       ...       ...       ...   
1663       100       100       100       100       100       100       100   
1664       100       100       100       100       100       100       100   
1665       100       100       100       100       100       100       100   
1670       100       100       100       100       100       100       100   
1671       100       100       100       100       100       100       100   

      word_170  
1          100  
2          100  
3          100  
4          100  
5          100  
...        ...  
1663       100  
1664       100  
1665       100  
1670       100  
1671       100  

[1147 rows x 170 columns]

In [116]:
import numpy as np
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import LSTM, Dense, Embedding

In [131]:
train_df

NameError: name 'train_df' is not defined

In [127]:
from tensorflow.keras.preprocessing.sequence import pad_sequences
X_padded = pad_sequences(A_tra_X.values, dtype='float32', padding='post')

# Example labels (replace with your actual labels)
y = np.array([0, 1, 0, 1, 1, 0, 0, 1, 1, 0])

# Define RNN model
model = Sequential([
    Embedding(input_dim=170, output_dim=11, input_length=10),
    LSTM(units=32),
    Dense(units=1, activation='sigmoid')
])

# Compile model
model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

# Train model
model.fit(X_padded, y, epochs=10, batch_size=32, validation_split=0.2)

# Evaluate model
loss, accuracy = model.evaluate(X_test_padded, y_test)
print(f'Test Loss: {loss}, Test Accuracy: {accuracy}')

# Make predictions
predictions = model.predict(X_new_data_padded)

ValueError: Data cardinality is ambiguous. Make sure all arrays contain the same number of samples.'x' sizes: 917
'y' sizes: 10
